export default {
    addImage: require('./addImage.png'),
    blur: require('./blur.png'),
    border: require('./border.png'),
    brightness: require('./brightness.png'),
    background: require('./background.png'),
    email: require('./email.png'),
    exit: require('./exit.png'),
    export: require('./export.png'),
    favorite: require('./favorite.png'),
    generator: require('./generator.png'),
    home: require('./home.png'),
    info: require('./info.png'),
    phone: require('./phone.png'),
    refresh: require('./refresh.png'),
    search: require('./search.png'),
    search: require('./search.png'),
    share: require('./share.png'),
    text: require('./text.png'),
    textSize: require('./textSize.png'),
}